on:
  workflow_call:
    inputs:
      variable:
        type: string
        required: true
      environment:
        type: string
        required: false
        default: development


jobs:
  display-input-variable:
    environment: ${{ inputs.environment }}
    name: Display input variable
    runs-on: ubuntu-latest
    steps:
      - name: Outputs variable
        run: echo ${{ vars.TEST_VAR_NAME }}