on:
  workflow_call:
    inputs:
      variable:
        type: string
        required: true


jobs:
  display-input-variable:
    name: Display input variable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Outputs variable
        run: echo ${{ inputs.variable }}